services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_data:/qdrant/storage  # Persistent storage
    restart: unless-stopped

  # Langfuse (Observability)
  langfuse:
    image: langfuse/langfuse:2  # Explicit version pin
    ports:
      - "3000:3000"  # Web UI
      - "3001:3001"  # API
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/langfuse?schema=public
      - NEXTAUTH_SECRET=f751b1b8ab3b492a0c59ccacaefd7799904c9278975e39a39b87260443ee10cd  # Generate via: openssl rand -hex 32
      - SALT=7d2abddf802fcf5378c8f5e276e4be5c1e2bdc708bcc09c7aac0d27201d94a3c           # Generate via: openssl rand -hex 32
    depends_on:
      - postgres
    restart: unless-stopped

  # Postgres (Required for Langfuse)
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=langfuse
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent DB storage
    restart: unless-stopped

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  qdrant_data:    # Qdrant storage
  postgres_data:  # Postgres DB
  redis_data:     # Redis DB